---

- name: Install UFW firewall
  apt: name="ufw"
  become: true

- name: Open firewall port for SSH (TCP 22)
  ufw: rule="allow" proto="tcp" port="22"
  become: true

#- debug: var=ports
- name: Open given ports {{ ports }} through firewall
  ufw: proto=any port={{ item }} rule=allow
  with_items: "{{ ports }}"
  when:
    - ports is defined
    - ports|length > 0
  become: true

- name: Set firewall default policy to deny incoming
  ufw: state=enabled direction=incoming policy=deny
  become: true
