---

- hosts: all

  gather_facts: true

  roles:
    - DATE_syncing
    - BOOT_config
    - OS_update
    - OS_reboot
    - DATE_syncing
    - SSH_firewall
    - BASH_profile
    - UTC_timezone
    - US_locale
    - DISABLE_swap
    - { role: NTP_client, ntp_config_server: '{{ ntp_servers }}' }
    - INSTALL_commons
    - INSTALL_seriallogger
    - { role: OS_hostname, hostname: "{{ inventory_hostname_short }}" }
    - { role: OS_reboot, waiting: no }
