---

- name: Install common tools
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - tree
    - unzip
    - firefox-esr
    - nautilus
    - gedit
    - meld
    - screen
    - tio
    - git
    - telnet
    - gawk
    - apt-file
    - pssh
    - nmap
