---

- name: Restarting the machine
  shell: sleep 3 && /sbin/shutdown -r now "Ansible reboot triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes

- name: Waiting for machine to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=100 port={{ ansible_ssh_port | default(22) }}
  when: waiting is undefined
