---

- name: Update '/etc/systemd/timesyncd.conf' with given NTP server(s) if any
  become: yes
  replace:
    backup: yes
    path: /etc/systemd/timesyncd.conf
    regexp: '^NTP=(.+)$'
    replace: NTP={{ ntp_config_server }}

- name: Add given NTP server(s) to '/etc/systemd/timesyncd.conf'
  become: yes
  replace:
    backup: yes
    path: /etc/systemd/timesyncd.conf
    regexp: '#NTP='
    replace: NTP={{ ntp_config_server }}

- name: Enable NTP servers fallback in '/etc/systemd/timesyncd.conf'
  become: yes
  replace:
    backup: yes
    path: /etc/systemd/timesyncd.conf
    regexp: '#FallbackNTP='
    replace: 'FallbackNTP='

- name: Disable NTP (systemd timesyncd) service
  become: yes
  command: timedatectl set-ntp off

- name: Enable NTP (systemd timesyncd) service
  become: yes
  command: timedatectl set-ntp on

- name: Show NTP (systemd timesyncd) status
  command: "timedatectl status"
  register: output
- debug: msg="{{ output.stdout }}"
#- debug: msg="{{ output.stderr }}"
