---

- set_fact: custom="arduino-1.8.16-linuxarm.tar.xz"
- set_fact: local="../files/{{ custom }}"
- set_fact: remote="~/{{ custom }}"
- name: Download package
  copy: mode="u+r" src={{ local }} dest={{ remote }}
  become: yes
- name: Unarchive package in /opt
  unarchive: src="{{ remote }}" dest="/opt/" copy=no
  become: yes
- name: Install package
  shell: "/opt/arduino-1.8.16/install.sh"
  become: yes

- set_fact: destination=~/.arduino15
- name: Creating directory
  file: path={{ destination }} state=directory
- name: Transfering files
  copy: mode="u+rwx" src=../files/{{ item }} dest={{ destination }}/
  with_items:
     - preferences.txt

- set_fact: custom="pololu-usb-avr-programmer-v2-1.1.0-linux-rpi.tar.xz"
- set_fact: local="../files/{{ custom }}"
- set_fact: remote="~/{{ custom }}"
- name: Download package
  copy: mode="u+r" src={{ local }} dest={{ remote }}
  become: yes
- name: Unarchive package in /opt
  unarchive: src="{{ remote }}" dest="/opt/" copy=no
  become: yes
- name: Install package
  shell: "/opt/pololu-usb-avr-programmer-v2-1.1.0-linux-rpi/install.sh"
  become: yes
